/**
 * Sprite SVG
 * WARNING: Do not edit this file unless you're aware of you're doing.
 * It is responsible to auto-load SVG files from `resources/images/sprite-svg`
 * folder and generate a `sprite.svg` file in `dist`.
 */
const icons = require.context('@images/sprite-svg', true, /\.svg$/);
icons.keys().forEach(icons);
